version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8081:8080"
      - "50051:50051"  # Needed for gRPC, which your error showed
    restart: always
    environment:
      QUERY_DEFAULTS_LIMIT: '25'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: './weaviate_data'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'none'
